buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.jmix.gradle:jmix-gradle-plugin:3.0.0"
    }
}

plugins {
    id 'com.vanniktech.maven.publish' version '0.37.0' apply false
}

group = 'io.github.makssent'
version = '3.0.0'

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.jmix'
    apply plugin: 'com.vanniktech.maven.publish'

    repositories {
        mavenCentral()
        maven { url = 'https://global.repo.jmix.io/repository/public' }
    }

    jmix {
        bomVersion = '3.0.0'
        projectId = 'firebird'
    }

    group = rootProject.group
    version = rootProject.version

    project.tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
        options.release = 17
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    publishing {
        publications.withType(MavenPublication).configureEach {
            versionMapping {
                usage('java-api') { fromResolutionResult() }
                usage('java-runtime') { fromResolutionResult() }
            }
        }
    }

    mavenPublishing {
        publishToMavenCentral()
        signAllPublications()

        coordinates(group.toString(), "jmix-${project.name}", version.toString())

        pom {
            name = "jmix-${project.name}"
            description = 'Firebird database support for Jmix applications'
            url = 'https://github.com/makssent/jmix-firebird-addon'
            inceptionYear = '2025'

            licenses {
                license {
                    name = 'The Apache License, Version 2.0'
                    url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                }
            }
            developers {
                developer {
                    id = 'makssent'
                    name = 'makssent'
                    url = 'https://github.com/makssent'
                }
            }
            scm {
                url = 'https://github.com/makssent/jmix-firebird-addon'
                connection = 'scm:git:git://github.com/makssent/jmix-firebird-addon.git'
                developerConnection = 'scm:git:ssh://git@github.com/makssent/jmix-firebird-addon.git'
            }
        }
    }
}