buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.jmix.gradle:jmix-gradle-plugin:3.0.0"
    }
}

group = 'io.github.makssent'
version = '0.1.0-SNAPSHOT'

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'io.jmix'

    repositories {
        mavenCentral()
        maven { url = 'https://global.repo.jmix.io/repository/public' }
    }

    jmix {
        bomVersion = '3.0.0'
        projectId = 'firebird'
    }

    group = this.group
    version = this.version

    java {
        withSourcesJar()
    }

    artifacts {
        archives sourcesJar
    }

    afterEvaluate {
        publishing {
            publications {
                javaMaven(MavenPublication) {
                    artifactId = project.base.archivesName.get()
                    from components.java
                }
            }
        }
    }

    // remove after https://youtrack.jetbrains.com/issue/IDEA-227215 is fixed
    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }

    project.tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
        options.release = 17
    }
}
